# Generated by Django 6.0.1 on 2026-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_is_used'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_phone_n_f2d675_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
